### ISSUE TITLE
Any idea?

### ISSUE THREAD

**Issue by ethanhe42** [MatthieuCourbariaux/BinaryConnect#3]
Building the CNN...
/home/eli/anaconda2/lib/python2.7/site-packages/lasagne/layers/conv.py:489: UserWarning: The `image_shape` keyword argument to `tensor.nnet.conv2d` is deprecated, it has been renamed to `input_shape`.
  border_mode=border_mode)
Traceback (most recent call last):
  File "cifar10.py", line 301, in <module>
    W_grads = binary_connect.compute_grads(loss,cnn)
  File "/home/eli/work/b2/BinaryConnect/binary_connect.py", line 163, in compute_grads
    grads.append(theano.grad(loss, wrt=layer.Wb))
AttributeError: 'Conv2DLayer' object has no attribute 'Wb'

**Comment by ecsark** [comment]
Check out commits earlier than 2b2a03f.

**Comment by rmr8019** [comment]
I am running into the same error. I am new to understanding the commits file that you've referenced, @ecsark ... what needs to be changed, more explicitly? 

Traceback (most recent call last):
  File "cifar10.py", line 301, in <module>
    W_grads = binary_connect.compute_grads(loss,cnn)
  File "//BinaryConnect/BinaryConnect/binary_connect.py", line 164, in compute_grads
    grads.append(theano.grad(loss, wrt=layer.Wb))
AttributeError: 'Conv2DLayer' object has no attribute 'Wb'

**Comment by roserustowicz** [comment]
I was running into the same issue, but made the changes back to the original before the commits as pointed out by @ecsark . It seems to be working now ... Thank you!

**Comment by bigbigda** [comment]
so why this happened, can anyone explain this?
